from crewai import Crew, Process
from models.LLM import llm
from datetime import datetime

from agents.SummariserAgent import summariser_agent
from agents.SentimentAgent import sentiment_agent
from agents.FetcherAgent import fetcher_agent
from tasks.FetchingTask import fetching_Task
from tasks.SummarisingTask import summarising_task
from tasks.SentimentAnalyseTask import sentiment_analyse_and_feature_extraction_task

crew = Crew(
    agents=[fetcher_agent,sentiment_agent,summariser_agent],
    tasks=[fetching_Task,sentiment_analyse_and_feature_extraction_task,summarising_task],
    process=Process.sequential,
    verbose=True,
)

product_query = input(
    'Enter the name of the product:\n'
)

result = crew.kickoff(inputs={'product_query': product_query})

markdown_output = f"""
# 📝 Product Review Summary for **{product_query}**

**🕒 Generated on:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## 🧠 Final Answer

> {result}

---

*Generated by CrewAI agents: Fetcher, Sentiment Analyzer, Summariser*
"""

# Save it to a Markdown file
filename = f"{product_query.lower().replace(' ', '_')}_summary.md"
with open(filename, "w", encoding="utf-8") as f:
    f.write(markdown_output)

print(f"\n✅ Summary saved to: {filename}")